name: Devdrama
markdown: redcarpet
redcarpet:
  extensions: [footnotes,strikethrough]
pygments: true

keywords: "MSSQL, Microsoft SQL, CLR, User-defined functions, CLR, SQL Server, tips, Sybase ASE UDF"
description: "Microsoft SQL tips"
